### ISSUE TITLE
Server Side Validation using this library

### ISSUE THREAD

**Issue by SigmaSoftSol** [Ninja-Squad/ngx-valdemort#128]
Hello Team,
   Can I create a custom validator where it will perform validation on the server side by using a custom function and based on the execution result it will show case the error.
  For example if I want to check the uniqueness of a user from the database, I will call an api to find out.  the api will return the true or false.  If true then the library should not emit the error.  If the output is false then it should display the error message.
 Is it possible in this library.  If available can you please share me the code snippet for the same.

Thanks & Regards,
Seshu Kumar.

**Comment by jnizet** [comment]
No, that's not what this library does. It only displays validation errors. But Angular supports that natively: it's called an async validator, and it's documented with examples in the standard documentation: https://angular.io/guide/form-validation#async-validation

**Comment by SigmaSoftSol** [comment]
Can we inject our own custom validators in to this library like min, max, required.

**Comment by jnizet** [comment]
You can't inject a validator, because this library doesn't use any validator. It only displays validation errors. And yes, you can display any kind of validation error you want: there is no difference errors triggered by standard and custom validators.

**Comment by SigmaSoftSol** [comment]
So if I write a custom async validation, then How can use this library to display the error.  Can you please let me know the way to display the validation error.

**Comment by jnizet** [comment]
The same way you display any other validation error with this library, as documented: https://ngx-valdemort.ninja-squad.com
