### ISSUE TITLE
Can it be used on a formGroup and a custom validator?

### ISSUE THREAD

**Issue by hervehobbes** [Ninja-Squad/ngx-valdemort#188]
Hello,

Imagine a form used to create a user profile, you have several fields and 2 of them are the first name and the last name. I created a custom Angular validator (and I attached it to the group) to verify if the first name is not equal to the last name.

Can I use ngx-valdemort in this case ?

Thanks

**Comment by jnizet** [comment]
Yes, you can. Since you want to display an error message for the group itself, you'll need to pass the group, and not the group name (since it doesn't have a name):
```
    <form [formGroup]="userProfileForm">
      ...
      <val-errors [control]="userProfileForm">
        <ng-template valError="customErrorKey">The first name and the last name should be different</ng-template>
      </val-errors>
    </form>
```

**Comment by hervehobbes** [comment]
It runs perfectly, thank you very much!
