### ISSUE TITLE
feature request: support for "generic" error message on invalid control

### ISSUE THREAD

**Issue by david-bulte** [Ninja-Squad/ngx-valdemort#265]
Would it be possible to show a generic message on *any* validation error *without having to list them all in the val-errors*. For example, if a control has both a 'required' and a 'min' validator, I would like to be able to show a generic message like "This is an invalid value", regardless of the validation error.

Something like so:

```
<val-errors>
  <ng-template [control]="ctrl">o o this is very wrong</ng-template>  <-- notice there is no valError
<val-errors>
```

**Comment by jnizet** [comment]
Hi @david-bulte 

I think the solution we proposed in your other issue (#264) should also address this one: if you don't specify any `valError`, but only a `valDefaultError`, it would effectively display this catch-all message for all errors. So, the possible scenarios would be the following ones:

## First scenario:

in the root component:
```html
 <val-default-errors>
  <ng-template valDefaultError>this field is invalid</ng-template>
</val-default-errors>
```

in form component:
```html
 <val-errors [control]="ctrl"></val-errors>
```

That would display the generic error message whatever the error is on the form control 

## Second scenario:

in the root component:
```html
 <val-default-errors>
  <ng-template valError="required">this field is mandatory<ng-template>
  <ng-template valDefaultError>this field is invalid</ng-template>
</val-default-errors>
```

in form component:
```html
 <val-errors [control]="ctrl"></val-errors>
```

That would display the specific mandatory message if the error is required, and the generic error message if the error is something else.

## Third scenario:

in the root component:
```html
 <val-default-errors>
  <ng-template valError="required">this field is mandatory<ng-template>
  <ng-template valDefaultError>this field is invalid</ng-template>
</val-default-errors>
```

in form component:
```html
<val-errors [control]="ctrl">
  <ng-template valError="minlength">this field is too short<ng-template>
  <ng-template valDefaultError>this field is really invalid</ng-template>
</val-errors>
```

That would display 
 - "this field is mandatory" if the error type is `required`
 - "this field is too short" if the error type is `minlength`
 - "this field is really invalid" if the error type is anything else

Does that suit your requirements?

**Comment by david-bulte** [comment]
Hi @jnizet, thanks for your answer, this looks very interesting.

The valDefaultError might be helpfull with regards to [https://github.com/Ninja-Squad/ngx-valdemort/issues/264](264). Our error messages are mainly managed in our translation system, so using valDefaultError I could do something like so:

```
<val-default-errors>
  <ng-template valDefaultError let-error="error">{{'errors.' + error.name | translate}}</ng-template>
</val-default-errors>
```

This would look up the key 'errors.required' in the translation system.

However I understand now that the "error" object I get a handle to, does not contain the error's name (e.g. 'required'). So I would also need something like "let-error-name", e.g.:

```
<val-default-errors>
  <ng-template valDefaultError let-error="error" **let-error-name="errorName"**>{{'errors.' + errorName | translate}}</ng-template>
</val-default-errors>
```


As for my other use case, this is really exceptional and maybe not worth the effort. But the requirement here is that in the component, I would catch all errors, and not check errors defined in de root component, f.e.

```
<val-errors [control]="ctrl">
  <ng-template **valCatchAllError**>this field is really invalid, no need to check the root for a more specific message</ng-template>
</val-errors>
```

**Comment by jnizet** [comment]
Sorry for the delay @david-bulte. 

Indeed, your second use-case looks too exceptional to us to justify a specific change in ngx-valdemort. It can relatively easily implemented by using `ngIf` and delegating to the ValdemortConfig service to decide when to display the error message. Something like: 

```
<form [formGroup]="form" #formGroupDirective="ngForm">
  <input formControlName="foo">
  <div *ngIf="form.get('foo').invalid && valdemortConfig.shouldDisplayErrors(form.get('foo'), formGroupDirective)">
    this field is really invalid
  </div>
</form>
```

We will implement the other request, i.e. adding a valDefaultError directive and exposing the error name/key to this directive in addition to the error itself and to the label.

**Comment by david-bulte** [comment]
Thanks guys, really appreciate it!

**Comment by jnizet** [comment]
You can have a look at the PR #270 to have a look at what we plan to release. Feel free to comment.
