### ISSUE TITLE
Using ngx-valdemort for validation input with [(ngModel)]

### ISSUE THREAD

**Issue by dominik-mrugalski** [Ninja-Squad/ngx-valdemort#290]
Hello,

I'm using this library and I like it, but I can't find a way how can I use that for input that isn't part of Reactive form but a standalone input field with [(ngModel)] attribute.

Is there a way to use it in this way?
Especially, I would like to use it with ng-select library:

```
<ng-select [items]="filterByList"
                     [(ngModel)]="filterById"
                     bindLabel="label"
                     (change)="onFilterChange($event)"
                     [ngModelOptions]="{standalone: true}"
                     notFoundText="No filters found"
                     bindValue="id"
                     placeholder="Select Filter By">
</ng-select>
```
Thanks for your help!

**Comment by cexbrayat** [comment]
👋 @dominik-mrugalski  

Sure, you need to grab the control and give it to `val-errors`.

You can probably do something like this:
```html
<ng-select [(ngModel)]="filterById" #fitlerCtrl="ngModel"/>
<val-errors [control]="fitlerCtrl.control"></val-errors>
```

You're right, we should add an example in the documentation (there are some examples in the codebase, but that's obviously hard to find). I'll open a PR to improve the documentation.

**Comment by cexbrayat** [comment]
I added a small example on the home page of the documentation https://ngx-valdemort.ninja-squad.com/#/
Hope this helps!

**Comment by dominik-mrugalski** [comment]
Thanks!
