### ISSUE TITLE
AoT build failed with Angular 6

### ISSUE THREAD

**Issue by qdelettre** [Ninja-Squad/ngx-valdemort#86]
Hi,

I'm using angular 6 with
`"ngx-valdemort": "^0.1.0",`

When building aot :
`ERROR in node_modules/ngx-valdemort/ngx-valdemort.d.ts.ɵa.html(3,19): : Object is possibly 'null'.`

**Comment by cexbrayat** [comment]
👋 Thank you for taking the time to open an issue.

I guess you are using `strictNullChecks` in your TypeScript configuration?

**Comment by jnizet** [comment]
@qdelettre I just released version 0.1.1. Please tell us if everything works fine with this release.

**Comment by qdelettre** [comment]
@jnizet Aot build is fine :+1: 
Thank you.
